# Generated by Django 3.0.11 on 2021-01-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usertaste_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertaste',
            name='recommendations',
        ),
    ]
