# Generate static angular files
FROM node:alpine as build

WORKDIR /app

COPY . . 

RUN npm install

RUN npm run build --prod


# Start nginx to host the files
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html