version: '3.7'

services:

  django:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    working_dir: /app
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    env_file:
      - .env.prod
    restart: on-failure
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: on-failure

  postgres:
    image: postgres
    volumes:
      - ./backend/db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.prod

volumes:
  db-data: