version: '3.7'

services: 
  django:
    build:
      context: .
    volumes:
      - static_data:/vol/web
    environment:
      - SECRET_KEY=samplesecret123
      - ALLOWED_HOSTS=127.0.0.1,localhost
    
  nginx:
    build:
      context: ./nginx
    volumes: 
      - static_data:/vol/static
    ports:
      - "8080:8080"
    depends_on: 
      - django

volumes:
  static_data: