version: '3.7'

services:

  django:
    build:
      context: backend
      dockerfile: Dockerfile.prod
    working_dir: /app
    container_name: django
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - 8000
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - postgres

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - 80:80
    env_file:
      - .env
    restart: on-failure

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - .env