# Generated by Django 3.0.11 on 2021-01-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210125_1250'),
        ('accounts', '0001_squashed_0007_auto_20210121_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaste',
            name='recommendations',
            field=models.ManyToManyField(to='games.BoardGame'),
        ),
    ]
