# Generated by Django 3.0.11 on 2021-01-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210112_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaste',
            old_name='number_of_reviews',
            new_name='number_of_ratings',
        ),
        migrations.AddField(
            model_name='usertaste',
            name='origin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
