# Generated by Django 3.0.11 on 2021-01-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaste',
            name='username',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
