# Generated by Django 3.0.11 on 2021-01-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_usertaste_recommendations'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_by'], name='accounts_re_created_4d7156_idx'),
        ),
    ]
