# Generated by Django 3.0.11 on 2021-01-21 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210120_1010'),
        ('accounts', '0005_auto_20210121_2021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('created_by', 'game')},
        ),
    ]
