# Generated by Django 3.0.11 on 2021-01-05 15:14
from __future__ import unicode_literals
from django.db import migrations


def create_initial_games(apps, schema_editor):
    BoardGame = apps.get_model('game', 'BoardGame')

    BoardGame(name='Monopoly', description='Fun strategy board game', price=26.99).save()
    BoardGame(name='Siedler', description='Board game', price=42).save()
    BoardGame(name='Uno', description='Fun card game', price=6.50).save()


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_games),
    ]
