# Generated by Django 3.0.11 on 2021-01-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bga_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_num_ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_price_us',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_rank_trending',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bga_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_avg_bayes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_avg_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_num_ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_num_user_comments',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='bgg_stddev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_number_of_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='max_playtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_number_of_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='min_playtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='official_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='reddit_all_time_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='similar_online_games',
            field=models.ManyToManyField(blank=True, null=True, through='games.SimilarBoardOnlineGame', to='games.OnlineGame'),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardgame',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='bga_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='bga_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='bga_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='bgg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='bgg_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gamemechanic',
            name='bga_id',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gamemechanic',
            name='bga_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='gamemechanic',
            name='bga_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamemechanic',
            name='bgg_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamemechanic',
            name='bgg_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='max_number_of_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='max_playtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='min_number_of_players',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='min_playtime',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='onlinegame',
            name='year_published',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='bga_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
