# Generated by Django 3.0.11 on 2021-01-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bga_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='bga_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bga_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bga_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bgg_id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='bgg_name',
        ),
        migrations.RemoveField(
            model_name='gamemechanic',
            name='bga_id',
        ),
        migrations.RemoveField(
            model_name='gamemechanic',
            name='bga_name',
        ),
        migrations.RemoveField(
            model_name='gamemechanic',
            name='bgg_id',
        ),
        migrations.RemoveField(
            model_name='gamemechanic',
            name='bgg_name',
        ),
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
