# Generated by Django 3.0.11 on 2021-01-25 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_squashed_0002_auto_20210120_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='recommendations',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='author',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='author',
            field=models.ManyToManyField(to='games.Author'),
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ManyToManyField(to='games.Category'),
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='game_mechanic',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='game_mechanic',
            field=models.ManyToManyField(to='games.GameMechanic'),
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='publisher',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='publisher',
            field=models.ManyToManyField(to='games.Publisher'),
        ),
        migrations.RemoveField(
            model_name='onlinegame',
            name='author',
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='author',
            field=models.ManyToManyField(to='games.Author'),
        ),
        migrations.RemoveField(
            model_name='onlinegame',
            name='category',
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='category',
            field=models.ManyToManyField(to='games.Category'),
        ),
        migrations.RemoveField(
            model_name='onlinegame',
            name='game_mechanic',
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='game_mechanic',
            field=models.ManyToManyField(to='games.GameMechanic'),
        ),
        migrations.RemoveField(
            model_name='onlinegame',
            name='publisher',
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='publisher',
            field=models.ManyToManyField(to='games.Publisher'),
        ),
    ]
