# Generated by Django 3.0.11 on 2021-01-28 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_itemsimilaritymatrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardgamePublisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.BoardGame')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Publisher')),
            ],
        ),
        migrations.CreateModel(
            name='BoardgameMechanic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.BoardGame')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameMechanic')),
            ],
        ),
        migrations.CreateModel(
            name='BoardgameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.BoardGame')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category')),
            ],
        ),
        migrations.CreateModel(
            name='BoardgameAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Author')),
                ('board_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.BoardGame')),
            ],
        ),

        migrations.RemoveField(
            model_name='boardgame',
            name='author',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='author',
            field=models.ManyToManyField(through='games.BoardgameAuthor', to='games.Author'),
        ),

        migrations.RemoveField(
            model_name='boardgame',
            name='category',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='category',
            field=models.ManyToManyField(through='games.BoardgameCategory', to='games.Category'),
        ),

        migrations.RemoveField(
            model_name='boardgame',
            name='game_mechanic',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='game_mechanic',
            field=models.ManyToManyField(through='games.BoardgameMechanic', to='games.GameMechanic'),
        ),

        migrations.RemoveField(
            model_name='boardgame',
            name='publisher',
        ),
        migrations.AddField(
            model_name='boardgame',
            name='publisher',
            field=models.ManyToManyField(through='games.BoardgamePublisher', to='games.Publisher'),
        ),

    ]
