# Generated by Django 3.0.11 on 2021-01-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20210128_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='similar_online_games',
        ),
        migrations.RemoveField(
            model_name='onlinegame',
            name='image_url',
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='bgg_id',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onlinegame',
            name='origin',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='SimilarBoardOnlineGame',
        ),
    ]
