# Generated by Django 3.0.11 on 2021-01-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20210129_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinegame',
            name='bgg_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
