# Generated by Django 3.0.11 on 2021-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20210129_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsimilaritymatrix',
            name='game_one',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itemsimilaritymatrix',
            name='game_two',
            field=models.FloatField(),
        ),
    ]
