# Generated by Django 3.0.11 on 2021-01-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20210131_2028'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itemsimilaritymatrix',
            index=models.Index(fields=['game_one'], name='games_items_game_on_cf85d5_idx'),
        ),
    ]
